### ISSUE TITLE
Not working at Windows 11 pro 23h2

### ISSUE THREAD

**Issue by lauvsong** [lauvsong/language-cursor#29]

**Comment by myoun** [comment]
언제 고쳐진 플러그인 업데이트 되나요?
사용하고 싶은데 한영키와 상관없이 빨간색으로 표시되는 문제만 해결되면 쓰고 싶어요.

**Comment by lauvsong** [comment]
@myoun 님 안녕하세요 :)
현재 해당 이슈 픽스된 버전으로 JetBrains 심사 중이고, 평일 화요일 쯤 승인으로 예상합니다.
마켓에 배포되면 여기 한번 더 코멘트 드리겠습니다!

**Comment by lauvsong** [comment]
1.0.3으로 해당 이슈 배포 완료되었습니다.
